//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLive.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeLive.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Home Live Plugins Settings
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=Tools
        ///DumperForm.decryptFromFilesToolStripMenuItem=Decrypt from files
        ///DumperForm.encryptFromFilesToolStripMenuItem=Encrypt from files
        ///DumperForm.loadFileToEditorToolStripMenuItem=Load file to Editor
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=Load files to Boxes
        ///Dum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Home Live Plugins Settings
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=Tools
        ///DumperForm.decryptFromFilesToolStripMenuItem=Decrypt from files
        ///DumperForm.encryptFromFilesToolStripMenuItem=Encrypt from files
        ///DumperForm.loadFileToEditorToolStripMenuItem=Load file to Editor
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=Load files to Boxes
        ///Dum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Opciones Home Live Plugins 
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=Herramientas
        ///DumperForm.decryptFromFilesToolStripMenuItem=Desencriptar de archivos
        ///DumperForm.encryptFromFilesToolStripMenuItem=Encriptar de archivos
        ///DumperForm.loadFileToEditorToolStripMenuItem=Cargar archivo al editor
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Home Live Plugins Settings
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=Tools
        ///DumperForm.decryptFromFilesToolStripMenuItem=Decrypt from files
        ///DumperForm.encryptFromFilesToolStripMenuItem=Encrypt from files
        ///DumperForm.loadFileToEditorToolStripMenuItem=Load file to Editor
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=Load files to Boxes
        ///Dum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Impostazioni Home Live Plugins
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=Strumenti
        ///DumperForm.decryptFromFilesToolStripMenuItem=Decritta da files
        ///DumperForm.encryptFromFilesToolStripMenuItem=Critta da files
        ///DumperForm.loadFileToEditorToolStripMenuItem=Importa file nell&apos;Editor
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=Importa files n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Home Live Plugins Settings
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=Tools
        ///DumperForm.decryptFromFilesToolStripMenuItem=Decrypt from files
        ///DumperForm.encryptFromFilesToolStripMenuItem=Encrypt from files
        ///DumperForm.loadFileToEditorToolStripMenuItem=Load file to Editor
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=Load files to Boxes
        ///Dum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Home Live Plugins Settings
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=Tools
        ///DumperForm.decryptFromFilesToolStripMenuItem=Decrypt from files
        ///DumperForm.encryptFromFilesToolStripMenuItem=Encrypt from files
        ///DumperForm.loadFileToEditorToolStripMenuItem=Load file to Editor
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=Load files to Boxes
        ///Dum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live插件
        ///Plugin.DumperPlugin=Home Live导出
        ///Plugin.ViewerPlugin=Home Live浏览
        ///Plugin.SettingsPlugin=Home Live插件设置
        ///
        ///DumperForm=Home Live导出
        ///DumperForm.toolsToolStripMenuItem=工具
        ///DumperForm.decryptFromFilesToolStripMenuItem=从文件解密
        ///DumperForm.encryptFromFilesToolStripMenuItem=从文件加密
        ///DumperForm.loadFileToEditorToolStripMenuItem=将文件加载到编辑器
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=将文件加载到盒子
        ///DumperForm.loadFolderToBoxesToolStripMenuItem=将文件夹加载到盒子
        ///DumperForm.grpConnection=连接
        ///DumperFo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh_Hans {
            get {
                return ResourceManager.GetString("lang_zh_Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.HomeLivePlugins=Home Live Plugins
        ///Plugin.DumperPlugin=Home Live Dumper
        ///Plugin.ViewerPlugin=Home Live Viewer
        ///Plugin.SettingsPlugin=Home Live Plugins Settings
        ///
        ///DumperForm=Home Live Dumper Plugin
        ///DumperForm.toolsToolStripMenuItem=工具
        ///DumperForm.decryptFromFilesToolStripMenuItem=從文件解密
        ///DumperForm.encryptFromFilesToolStripMenuItem=從文件加密
        ///DumperForm.loadFileToEditorToolStripMenuItem=將文件加載到編輯器
        ///DumperForm.loadFilesToBoxesToolStripMenuItem=將文件加載到盒子
        ///DumperForm.loadFolderToBoxesToolStripMenuItem=Load fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh_Hant {
            get {
                return ResourceManager.GetString("lang_zh_Hant", resourceCulture);
            }
        }
    }
}
