//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOME.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOME.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderForm.grpSAV=Save File
        ///TeraFinderForm.grpSavTools=SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderForm.grpSAV=Save File
        ///TeraFinderForm.grpSavTools=SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderForm.grpSAV=Save File
        ///TeraFinderForm.grpSavTools=SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderForm.grpSAV=Save File
        ///TeraFinderForm.grpSavTools=SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connetti a Dispositivo Remoto
        ///Plugin.TeraViewer=Visualizza e Modifica Raid
        ///Plugin.SeedChecker=Controlla Seed
        ///Plugin.FlagEditor=Modifica Flags di Gioco
        ///Plugin.NewsImporter=Importa Raid Evento
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Strumenti
        ///TeraFinderForm.btnRemoteConnect=Connetti a Dispositivo Remoto
        ///TeraFinderForm.languageToolStrip=Lingua Predefinita
        ///TeraFinderForm.grpSAV=Salvataggio
        ///TeraFinderFo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderForm.grpSAV=Save File
        ///TeraFinderForm.grpSavTools=SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderForm.grpSAV=Save File
        ///TeraFinderForm.grpSavTools=SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=太晶洞窟搜索插件
        ///Plugin.ConnectRemote=远程连接
        ///Plugin.TeraViewer=太晶洞窟查看/编辑
        ///Plugin.SeedChecker=太晶洞窟Seed检索
        ///Plugin.FlagEditor=编辑太晶洞窟解锁进度
        ///Plugin.NewsImporter=导入宝可梦入口站新闻
        ///
        ///TeraFinderForm=太晶洞窟搜索
        ///TeraFinderForm.remoteConnectToolStripMenuItem=工具
        ///TeraFinderForm.btnRemoteConnect=远程连接
        ///TeraFinderForm.languageToolStrip=语言设置
        ///TeraFinderForm.grpSAV=存档文件
        ///TeraFinderForm.grpSavTools=存档工具
        ///TeraFinderForm.grpStaticTools=独立工具
        ///TeraFinderForm.btnLoad=读取存档文件
        ///TeraFinderForm.btnExport=导出存档文件
        ///TeraFinderForm.b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.TeraFinderPlugin=Tera Finder Plugin
        ///Plugin.ConnectRemote=Connect to Remote Device
        ///Plugin.TeraViewer=Tera Raid Viewer/Editor
        ///Plugin.SeedChecker=Tera Raid Seed Checker
        ///Plugin.FlagEditor=Edit Game Flags
        ///Plugin.NewsImporter=Import Poké Portal News
        ///
        ///TeraFinderForm=Tera Finder 
        ///TeraFinderForm.remoteConnectToolStripMenuItem=Tools
        ///TeraFinderForm.btnRemoteConnect=Connect To Remote Device
        ///TeraFinderForm.languageToolStrip=Default Language
        ///TeraFinderForm.grpSAV=Save File
        ///TeraFinderForm.grpSavTools=SA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh2 {
            get {
                return ResourceManager.GetString("lang_zh2", resourceCulture);
            }
        }
    }
}
